; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
[Setup]
AppName=Device Manager
AppVerName=Device Manager
DefaultDirName={pf}\RKDM
DefaultGroupName=Device Manager
OutputDir=Setup
OutputBaseFilename=DM_Setup
Compression=lzma
SolidCompression=yes

;[Languages]
;Name: English; MessagesFile: compiler:Default.isl
;Name: French; MessagesFile: compiler:Languages\French.isl
;Name: German; MessagesFile: compiler:Languages\German.isl
;Name: Russian; MessagesFile: compiler:Languages\Russian.isl
;Name: Portuguese; MessagesFile: compiler:Languages\Portuguese.isl
;Name: Chinese; MessagesFile: compiler:Languages\ChineseSimp.isl
;Name: Spanish; MessagesFile: compiler:Languages\Spanish.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
Source: Bin\*; DestDir: {app}\; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[INI]
;Filename: {app}\setting.ini; Section: SYSTEM; Key: LANGUAGE; String: {code:GetString}; Flags: createkeyifdoesntexist; Tasks: ; Languages:

[Icons]
Name: {group}\Device Manager; Filename: {app}\RKDeviceManage.exe ;WorkingDir: "{app}"
Name: {group}\{cm:UninstallProgram,Device Manager}; Filename: {uninstallexe}
Name: {commondesktop}\Device Manager; Filename: {app}\RKDeviceManage.exe; Tasks: desktopicon;WorkingDir: "{app}"

[Run]
Filename: {app}\RKDeviceManage.exe; Description: {cm:LaunchProgram,Device Manager}; Flags: nowait postinstall skipifsilent

[Code]
//var
//  UserPage: TInputQueryWizardPage;
 // ComboBox: TComboBox;
 // Page: TWizardPage;
  
//procedure InitializeWizard;
//begin
//  Page := CreateCustomPage(wpWelcome, 'Select Language', '');
//  ComboBox := TComboBox.Create(Page);
//  ComboBox.Width := Page.SurfaceWidth;
 // ComboBox.Parent := Page.Surface;
//  ComboBox.Style := csDropDownList;
//  ComboBox.Items.Add('Chinese');
 // ComboBox.Items.Add('English');
//  ComboBox.Items.Add('French');
//  ComboBox.Items.Add('German');
//  ComboBox.Items.Add('Portuguese');
//  ComboBox.Items.Add('Russian');
//  ComboBox.Items.Add('Spanish');
 // ComboBox.ItemIndex := 0;
//end;

//function GetString(aa:String): String;
//此程式依當時語系與傳入代碼，取回對應的文字

//begin
//  Result := ComboBox.Text;

//  if ComboBox.ItemIndex=0 then
//  begin
//    Result := 'English';
//  end
  
//  if ComboBox.ItemIndex=1 then
//  begin
//    Result := 'Chinese';
//  end
  
//  if ComboBox.ItemIndex=2 then
//  begin
//    Result := 'Spanish';
//  end
  
//end;


